/* module.exports = {
  VITE_REACT_APP_AUTH0_DOMAIN: import.meta.env.VITE_REACT_APP_AUTH0_DOMAIN,
  VITE_REACT_APP_AUTH0_CLIENT_ID: import.meta.env
    .VITE_REACT_APP_AUTH0_CLIENT_ID,
  VITE_REACT_APP_AUTH0_CALLBACK_URL: import.meta.env
    .VITE_REACT_APP_AUTH0_CALLBACK_URL,
  VITE_REACT_APP_AUTH0_AUDIENCE: import.meta.env.VITE_REACT_APP_AUTH0_AUDIENCE,
  VITE_REACT_APP_API_URL: import.meta.env.VITE_REACT_APP_API_URL,
  VITE_REACT_APP_FRONTEND_URL: import.meta.env.VITE_REACT_APP_FRONTEND_URL,
}; */

/* export const VITE_REACT_APP_AUTH0_DOMAIN = import.meta.env
  .VITE_REACT_APP_AUTH0_DOMAIN;
export const VITE_REACT_APP_AUTH0_CLIENT_ID = import.meta.env
  .VITE_REACT_APP_AUTH0_CLIENT_ID;
export const VITE_REACT_APP_AUTH0_CALLBACK_URL = import.meta.env
  .VITE_REACT_APP_AUTH0_CALLBACK_URL;
export const VITE_REACT_APP_AUTH0_AUDIENCE = import.meta.env
  .VITE_REACT_APP_AUTH0_AUDIENCE;
export const VITE_REACT_APP_API_URL = import.meta.env.VITE_REACT_APP_API_URL;
export const VITE_REACT_APP_FRONTEND_URL = import.meta.env
  .VITE_REACT_APP_FRONTEND_URL; */
